name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  dummy-secret:
    description: 'Use this to test out using a secret to do something'
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
  - run: |
      echo 'I wont run but I will try to say: Hello ${{ inputs.who-to-greet }}.'
    if: inputs.who-to-greet == 'World'
    shell: bash

  - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    shell: bash
  - run: |
      secret-leaker.sh "${{ inputs.dummy-secret }}"
    shell: bash

  - run: "echo oops we leaked a secret: '${{ inputs.dummy-secret }}'"
    shell: bash

  - id: random-number-generator
    run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
    shell: bash
